[package]
name = "jmc-tools"
version = "0.0.2"
authors = ["KillerJmc <1934497212@qq.com>"]
description = "Utils for Rust daily coding."
edition = "2021"

exclude = ["*.iml", ".*", "/tests"]

license = "MIT"
readme = "README.md"
repository = "https://github.com/KillerJmc/jmc-tools"

[dependencies]
